name: spec
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_14
  - libgcc-ng=15.2.0=h69a702a_14
  - libgomp=15.2.0=he0feb66_14
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=h3691f8a_5
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - backports-tarfile==1.2.0
      - black==25.11.0
      - build==1.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cryptography==46.0.3
      - datasets==4.4.1
      - dill==0.4.0
      - docutils==0.22.3
      - exceptiongroup==1.3.1
      - filelock==3.19.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - id==1.5.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - isort==7.0.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jeepney==0.9.0
      - jinja2==3.1.6
      - keyring==25.7.0
      - librt==0.6.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mypy==1.19.0
      - mypy-extensions==1.1.0
      - networkx==3.3
      - nh3==0.3.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - peft==0.18.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - propcache==0.4.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pycparser==2.23
      - pygments==2.19.2
      - pyproject-hooks==1.2.0
      - pytest==9.0.1
      - pytest-benchmark==5.2.3
      - python-dateutil==2.9.0.post0
      - pytokens==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - readme-renderer==44.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==14.2.0
      - ruff==0.14.7
      - safetensors==0.7.0
      - secretstorage==3.5.0
      - sentencepiece==0.2.1
      - six==1.17.0
      - sympy==1.14.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.0+cu126
      - torchaudio==2.9.0+cu126
      - torchvision==0.24.0+cu126
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.5.0
      - twine==6.2.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /home/ubuntu/miniforge3/envs/spec
